make check
#   $ docker compose down --volumes --remove-orphans
#

version: '3.7'

name: libvmod-valkey-master

services:
  dev:
    hostname: dev
    build:
      context: .
      no_cache: true
    privileged: true
    environment:
      HOST_UID: ${UID:?}
      HOST_GID: ${GID:?}
    volumes:
      - .:/mnt/host.raw
    tmpfs:
      - /run
      - /run/lock
      - /var/cache
      - /tmp:exec
